version: '3.7'
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      
    volumes:
      - "./mongo/bk:/bk"
      - "./mongo/data:/data/db"

    networks:
      network-db:
        ipv4_address: 174.20.0.4

  mongo-express:
    image: mongo-express
    container_name: mongo-express-interface
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance 
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on: 
      - mongo
    networks:
      network-db:
        ipv4_address: 174.20.0.5

networks:
  network-db:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 174.20.0.0/24